### ISSUE TITLE
Show PRs issued in data points on hover or click

### ISSUE THREAD

**Issue by n07734** [n07734/community-health#10]
There is potentially a lot of useful information shown in the data, but person needs to hunt in the repo to find the PRs related to the point of interest. 

Maybe on click a modal or new page showing the PR/PRs in that dataset.

**Comment by n07734** [comment]
There is an onclick bug raised for responsive line https://github.com/plouc/nivo/issues/608

Onclick works for Bar charts

**Comment by n07734** [comment]
For bar charts need to add links to PRs in the data so can use with the onclick, try listing prs in a modal

**Comment by ShuibCodes** [comment]
Hi, is there a way I can click on a bar and render something on the screen, like an svg or html element? is this possible for any of the charts?

**Comment by n07734** [comment]
There is an `onClick` prop https://nivo.rocks/bar/. Bug is it does not work with the responsive version of the charts which is the version I am using

**Comment by ShuibCodes** [comment]
i see, thanks

**Comment by n07734** [comment]
Added PR/Issues table below graph so related items can be found
